.\" $Id$
.TH UNIQBEG 7WN "30 Sept 1995" "WordNet 1.6" "WordNet\(tm"
.SH NAME
uniqbeg \- unique beginners for noun hierarchies
.SH DESCRIPTION
All of the WordNet noun synsets are organized into hierarchies.  Each
synset is part of at least one hierarchy, headed by a synset called a
unique beginner.  All of these synsets originate in the lexicographer
file \fBnoun.Tops\fP.  From any noun synset, except a unique beginner,
the hypernym pointers can be traced up to one of the following
synsets:

.RS
.nf
{ entity, something, (anything having existence (living or nonliving)) } 

{ psychological_feature, (a feature of the mental life of a living organism) }

{ abstraction, (a general concept formed by extracting common features from specific examples) }

{ state, (the way something is with respect to its main attributes; "the current state of knowledge"; 
	"his state of health"; "in a weak financial state") }

{ event, (something that happens at a given place and time) }

{ act, human_action, human_activity, (something that people do or cause to happen) }

{ group, grouping, (any number of entities (members) considered as a unit) }

{ possession, (anything owned or possessed) }

{ phenomenon, (any state or process known through the senses rather than by intuition or reasoning) }
.fi
.RE
.SH NOTES
The lexicographer files are not included in the WordNet package.
.SH FILES
.TP 20
.B noun.Tops
unique beginners for nouns
.SH SEE ALSO
.BR wndb (5WN),
.BR wninput (5WN),
.BR wngloss (7WN).
